services:
  php:
    container_name: docker_php_knowledge
    image: php-practice
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - '../.:/usr/src/php'
    networks:
      - php
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    volumes:
      - php_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    networks:
      - php

volumes:
  php_db: {}

networks:
  php: {}