run-php:
	docker-compose run --rm php /bin/bash

run-php-8:
	docker-compose run --rm php8.0 /bin/bash

run-port:
	docker-compose run --rm -p 3000:3000 php /bin/bash

up:
	docker-compose up -d

stop:
	docker-compose stop

status:
	docker-compose ps

force:
	docker-compose up -d --build --force-recreate