<?php

class ParentClass
{
    public function something(): void
    {

    }

}

class ChildClass extends ParentClass
{
    #[Override]
    public function something(): void
    {
        parent::something(); // TODO: Change the autogenerated stub
    }
}